### ISSUE TITLE
Scopes should use exists? rather than checking for inclusion in an id list, by default

### ISSUE THREAD

**Issue by philomory** [makandra/consul#23]
For powers that return ActiveRecord::Relations, `default_include_object` should use `exists?(object)` rather than plucking the ids from the scope and checking to see if the provided object's id is in the list. Plucking ids doesn't perform all _that_ badly, but, `exists?` will still always perform better. What's more, it will work in weird edge cases where the primary_key column is not called `id` (and there is no id column, or the id column is non-unique for some reason), because `exists?` will call `to_key` on its argument, rather than just using `id`.

On that note, even if it turns out that using `exists?` isn't a good idea, you might consider switching to collecting primary keys, rather than explicitly grabbing the id attribute.

**Comment by henning-koch** [comment]
Plucking primary keys instead of IDs: Would definitely be an improvement for scope-based powers.

The reason why we pluck IDs is that we often display a list of eg. 50 records that each have an `[EDIT]` button. Plucking IDs saves us from making 50 database queries for the decision whether or not to display that button.

I guess we could have an option that switches between the behavior

    current_power.updatable_card?(card, batch: false)
    current_power.updatable_card?(card, batch: true)

We would need to have some discussion about which the default should be for that, since making `batch: false` the default would be a breaking change. @kratob @codener 

If we go that route, we should also make sure that our memoization between both batch and non-batch check is consistent.

**Comment by philomory** [comment]
I tend (just as a matter of personal preference) not to use the 'big list of records each with a show, edit and destroy link', so the only conditions that I ran into were directly iterating over the scope, or checking an individual record; it somehow didn't occur to me that you might iterate over one scope and then check each record in it for membership in another scope as part of rendering your view.

Now that you've pointed that out, I don't think switching to exists? is likely to be worth it. The benefits of a single exists? statement over a single pluck + includes? are real, but I suspect they are vastly overshadowed by penalty you pay when doing fifty exists? DB calls rather than a single pluck + fifty includes?. Where it comes up in my own codebase I can just manually write the exists? call.

(That said, if you do want to get fancy about it, rails precedent seems to suggest defaulting to a exists? query for the single case, and providing some sort of eager loading option if you know in advance you're going to need a lot of them; again, possibly not worth the effort, but it's up to you).

**Comment by triskweline** [comment]
Closing this story since we don't want to make this the default behavior.

As shown above, users who want to use `exists?` can simply call `exists?`  on a power scope.
